# Generated by Django 3.2.8 on 2021-12-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info_digitform',
            old_name='ContactUs_Desciption',
            new_name='ContactUs_Description',
        ),
    ]
