# Generated by Django 3.2.8 on 2022-01-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0002_rename_contactus_desciption_info_digitform_contactus_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameAndFamily', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=100)),
                ('Text', models.TextField()),
                ('DateTimeSubmit', models.DateTimeField(auto_now_add=True)),
                ('Show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Answer', models.TextField()),
                ('DateTimeSubmit', models.DateTimeField(auto_now_add=True)),
                ('Show', models.BooleanField(default=False)),
            ],
        ),
    ]
