# Generated by Django 3.2.8 on 2021-12-09 01:34

import FormSaz.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BASE_ELEMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Element', models.CharField(max_length=30)),
                ('Type', models.CharField(max_length=20)),
                ('OnlyCreate', models.BooleanField(default=False)),
                ('STATUS', models.CharField(default='OK', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='CONFIG_BASE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DICT_CONFIG', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CONFIG_BASE_FORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DICT_CONFIG', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CONFIG_BASE_QUIZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DICT_CONFIG_QUIZ', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='STYLE_BASE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DICT_STYLE', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VALIDATION_BASE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DICT_VALIDATION', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AUDIO_BASE',
            fields=[
                ('base_element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormSaz.base_element')),
                ('Audio', models.FileField(null=True, upload_to=FormSaz.models.UploadElementAudioSrc)),
                ('Audio_Url', models.SlugField(blank=True, null=True)),
                ('STATE', models.CharField(default='__Init__', max_length=7)),
            ],
            bases=('FormSaz.base_element',),
        ),
        migrations.CreateModel(
            name='BOX_ELEMENT',
            fields=[
                ('base_element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormSaz.base_element')),
            ],
            bases=('FormSaz.base_element',),
        ),
        migrations.CreateModel(
            name='IMAGE_BASE',
            fields=[
                ('base_element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormSaz.base_element')),
                ('Image', models.ImageField(null=True, upload_to=FormSaz.models.UploadElementImageSrc)),
                ('Image_Url', models.SlugField(blank=True, null=True)),
                ('STATE', models.CharField(default='__Init__', max_length=7)),
            ],
            bases=('FormSaz.base_element',),
        ),
        migrations.CreateModel(
            name='INPUT_BASE',
            fields=[
                ('base_element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormSaz.base_element')),
            ],
            bases=('FormSaz.base_element',),
        ),
        migrations.CreateModel(
            name='PAGE_ELEMENT',
            fields=[
                ('base_element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormSaz.base_element')),
                ('COUNTER_ID_PAGE', models.IntegerField()),
            ],
            bases=('FormSaz.base_element',),
        ),
        migrations.CreateModel(
            name='TAG_H1',
            fields=[
                ('base_element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormSaz.base_element')),
            ],
            bases=('FormSaz.base_element',),
        ),
        migrations.CreateModel(
            name='TAG_H3',
            fields=[
                ('base_element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormSaz.base_element')),
            ],
            bases=('FormSaz.base_element',),
        ),
        migrations.CreateModel(
            name='TAG_H6',
            fields=[
                ('base_element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormSaz.base_element')),
            ],
            bases=('FormSaz.base_element',),
        ),
        migrations.CreateModel(
            name='TAG_P',
            fields=[
                ('base_element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormSaz.base_element')),
            ],
            bases=('FormSaz.base_element',),
        ),
        migrations.CreateModel(
            name='VIDEO_BASE',
            fields=[
                ('base_element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormSaz.base_element')),
                ('Video', models.FileField(null=True, upload_to=FormSaz.models.UploadElementVideoSrc)),
                ('Video_Url', models.SlugField(blank=True, null=True)),
                ('STATE', models.CharField(default='__Init__', max_length=7)),
            ],
            bases=('FormSaz.base_element',),
        ),
        migrations.CreateModel(
            name='FORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_FORM', models.CharField(default=FormSaz.models.RandomString, max_length=50)),
                ('Title', models.CharField(default='', max_length=150)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Type', models.CharField(default='Customize', max_length=30)),
                ('DateTimeCreate', models.DateTimeField(auto_now_add=True)),
                ('Form_Edited', models.BooleanField(default=False)),
                ('Config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormSaz.config_base_form')),
            ],
        ),
    ]
