# Generated by Django 3.2.8 on 2021-12-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormSaz', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_element',
            name='Type_Base',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
