# Generated by Django 3.2.8 on 2021-12-18 04:21

import FormSaz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormSaz', '0006_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='TrackingCode',
            field=models.CharField(default=FormSaz.models.RandomString, max_length=30),
        ),
    ]
