# Generated by Django 3.2.8 on 2021-12-18 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormSaz', '0007_record_trackingcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='Form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FormSaz.form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='Form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FormSaz.form'),
            preserve_default=False,
        ),
    ]
