# Generated by Django 3.2.8 on 2021-12-19 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormSaz', '0008_auto_20211218_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserCode', models.CharField(max_length=30)),
                ('InfoDevice', models.TextField()),
                ('DateTimeSubmit', models.DateTimeField(auto_now_add=True)),
                ('Form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormSaz.form')),
            ],
        ),
    ]
