# Generated by Django 3.2.8 on 2021-12-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormSaz', '0009_viewrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='InfoDevice',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
