# Generated by Django 3.2.8 on 2021-12-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormSaz', '0010_record_infodevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='IP',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewrecord',
            name='IP',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
