# Generated by Django 3.2.8 on 2021-12-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormSaz', '0011_auto_20211219_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='IsChecked',
            field=models.BooleanField(default=False),
        ),
    ]
