# Generated by Django 3.2.8 on 2021-12-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormSaz', '0012_record_ischecked'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='DateTimeSubmitMessage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='Meessage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
