# Generated by Django 3.2.8 on 2021-12-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormSaz', '0014_rename_meessage_record_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='TrackingCode',
            field=models.CharField(max_length=30),
        ),
    ]
