# Generated by Django 3.2.8 on 2021-12-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='IntroductionCode',
            field=models.CharField(default='O530PRTH', max_length=15),
        ),
    ]
