# Generated by Django 3.2.8 on 2021-12-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_user_introductioncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='IntroductionCode',
            field=models.CharField(default='C4VZUW2T', max_length=15),
        ),
    ]
