# Generated by Django 3.2.8 on 2022-01-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_alter_user_introductioncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='IntroductionCode',
            field=models.CharField(default='8BH0FXDX', max_length=15),
        ),
    ]
