# Generated by Django 3.2.8 on 2022-01-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_alter_user_introductioncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='IntroductionCode',
            field=models.CharField(default='INW0Q395', max_length=15),
        ),
    ]
